export const phrases: Set<string> = new Set([
  "Apologies, I couldn't sign in",
  "Apologies, I couldn't access",
  'Experienced connectivity problems',
  "I'm in a meeting",
  'Child is fussing',
  'Dog is howling',
  'Cat is purring',
  'Kettle is whistling',
  'Delivery person at the door',
  'Must take a crucial call',
  'Received a message',
  'Need a restroom break',
  'Need to grab a beverage',
  'Need to grab a snack',
  'Need to make some tea',
  'I was accidentally muted',
  'Having microphone issues',
  'Having camera issues',
  'Having issues sharing my screen',
  'Having issues sharing files',
  'Having issues with the interactive board',
  'Having issues with the chat',
  'Having issues with breakout groups',
  'Computer updating',
  'Browser overloaded',
  "My apologies, couldn't log in",
  "My apologies, couldn't join",
  'Had network issues',
  "I'm on another call",
  'Child is upset',
  'Dog is whimpering',
  'Cat is hissing',
  'Microwave beeping',
  'Courier at the door',
  'Important call coming through',
  'Just got a notification',
  'Need a bathroom break',
  'Need to refill my drink',
  'Need to grab a bite',
  'Need to brew some coffee',
  'My mic was off',
  'Having trouble with audio',
  'Having trouble with video',
  'Having trouble sharing my screen',
  'Having trouble sharing documents',
  'Having trouble with the digital board',
  'Having trouble with the messaging',
  'Having trouble with the discussion groups',
  'Software update',
  'Multiple windows open',
  "Sorry, couldn't sign on",
  "Sorry, couldn't attend",
  'Internet connection unstable',
  "I'm in a conference call",
  'Infant is crying',
  'Dog is growling',
  'Cat is yowling',
  'Oven timer going off',
  'Parcel delivery at the door',
  'Unexpected call coming in',
  'Received an alert',
  'Need a quick break',
  'Need to hydrate',
  'Need to eat something',
  'Need to prepare a hot drink',
  'Forgot to unmute',
  'Having sound issues',
  'Having display issues',
  'Having problems sharing my screen',
  'Having problems sharing resources',
  'Having problems with the virtual board',
  'Having problems with the conversation',
  'Having problems with group work',
  'System update',
  'Too many applications open',
  "Excuse me, couldn't log in",
  "Excuse me, couldn't join",
  'Lost internet connection',
  "I'm on a phone call",
  'Toddler is whining',
  'Dog is yelping',
  'Cat is screeching',
  'Stove alarm sounding',
  'Package delivery at the door',
  'Emergency call coming through',
  'Got an email',
  'Need a short break',
  'Need to quench my thirst',
  'Need to grab some lunch',
  'Need to make hot cocoa',
  'Microphone was off',
  'Having issues with my audio',
  'Having issues with my video',
  'Having issues with screen sharing',
  'Having issues with resource sharing',
  'Having issues with the electronic board',
  'Having issues with the text chat',
  'Having issues with collaborative sessions',
  'Device update',
  'Too many programs open',
  "Apologies, couldn't connect",
  "Apologies, couldn't participate",
  'Wi-Fi connection dropped',
  "I'm on a video call",
  'Newborn is fussing',
  'Dog is snarling',
  'Cat is growling',
  'Smoke alarm going off',
  'Grocery delivery at the door',
  'Urgent call just arrived',
  'Got a voicemail',
  'Need a minute',
  'Need to wet my whistle',
  'Need to fetch a meal',
  'Need to make a cup of tea',
  "Wasn't aware I was muted",
  'Having trouble with my audio',
  'Having trouble with my video',
  'Having trouble with sharing my screen',
  'Having trouble with sharing content',
  'Having trouble with the smart board',
  'Having trouble with the instant chat',
  'Having trouble with teamwork sessions',
  'Hardware update',
  'Excessive tabs open',
  "My bad, couldn't access",
  "My bad, couldn't come in",
  'Network connection lost',
  "I'm on a Zoom call",
  'Kid is throwing a tantrum',
  'Dog is sniffing',
  'Cat is scratching',
  'Alarm clock ringing',
  'Neighbor at the door',
  'Received an urgent call',
  'Got an instant message',
  'Need a breather',
  'Need to take a sip',
  'Need to fetch some dinner',
  'Need to steep some tea',
  "Didn't realize I was muted",
  'Having a problem with my audio',
  'Having a problem with my video',
  'Having a problem with screen sharing',
  'Having a problem with content sharing',
  'Having a problem with the online board',
  'Having a problem with the live chat',
  'Having a problem with the virtual groups',
  'Firmware update',
  'Running several tasks',
  "Pardon me, couldn't log on",
  "Pardon me, couldn't enter",
  'Internet was down',
  "I'm on a Skype call",
  'Child is throwing a fit',
  'Dog is panting',
  'Cat is pawing',
  'Coffee maker beeping',
  'Friend at the door',
  'Answering a vital call',
  'Received a DM',
  'Need a moment',
  'Need to sip some water',
  'Need to fetch some breakfast',
  'Need to pour a cup of coffee',
  'I had my microphone muted',
  'Having an issue with my audio',
  'Having an issue with my video',
  'Having an issue with sharing my screen',
  'Having an issue with sharing files',
  'Having an issue with the digital whiteboard',
  'Having an issue with the group chat',
  'Having an issue with the virtual meetings',
  'Operating system update',
  'Busy multitasking',
  "Forgive me, couldn't sign in",
  "Forgive me, couldn't be there",
  'Router rebooted',
  "I'm on a Teams call",
  'Child needs attention',
  'Dog is scratching',
  'Cat is stretching',
  'Dishwasher beeping',
  'Family member at the door',
  'Just got a crucial call',
  'Received a social media notification',
  'Need a pause',
  'Need to sip some juice',
  'Need to prepare a meal',
  'Need to get a cup of espresso',
  "Didn't know I was muted",
  'Driver update',
  'Juggling tasks',
  "Apologies, I wasn't able to log in",
  "Apologies, I couldn't make it",
  'Lost Wi-Fi signal',
  "I'm on a Google Meet call",
  'Baby needs changing',
  'Dog is sneezing',
  'Cat is licking',
  'Washing machine buzzing',
  'Co-worker at the door',
  'Handling an important call',
  'Got a LinkedIn message',
  'Need a timeout',
  'Need to sip some soda',
  'Need to cook some food',
  'Need to get an energy drink',
  'Mute button was on',
  'Having a glitch with my audio',
  'Having a glitch with my video',
  'Having a glitch with screen sharing',
  'Having a glitch with sharing presentations',
  'Having a glitch with the online drawing board',
  'Having a glitch with the group messaging',
  'Having a glitch with remote teamwork',
  'Software installation',
  'Multitasking overload',
  'Patch installation',
  'Overwhelmed with tasks',
]);
